### ISSUE TITLE
Add a patch for the CKEditor Media Resize module on Issue #3458385: Drupal core 10.3 breaks compatibility with CKEditor5 API

### ISSUE THREAD

**Issue by Arman-Ammar** [Vardot/varbase-patches#60]

**Comment by Natshah** [comment]
Good news :) ..

they had 2 important fixes .

they corrected the filter name, which we had issue with that in the past week.

[CKEditor Media Resize](https://www.drupal.org/project/ckeditor_media_resize) 1.0.0-beta2 was released on: 19 Aug 2024 by: [damienmckenna](https://www.drupal.org/user/108450)

https://www.drupal.org/project/ckeditor_media_resize/releases/1.0.0-beta2 

Bug
[#3380686](https://www.drupal.org/node/3380686) : Unable to install due to unmet dependencies.

[#3458385](https://www.drupal.org/node/3458385) : Drupal core 10.3 breaks compatibility with CKEditor5 API.

Task
[#3468893](https://www.drupal.org/node/3468893): Correct filter name.

The following Patch and PR are no longer needed

[Add a patch for the CKEditor Media Resize module on Issue #3458385: Drupal core 10.3 breaks compatibility with CKEditor5 API #60](https://github.com/Vardot/varbase-patches/issues/60)

Closing the PR in Varbase Patches
